Remote screen resolution
InsightSoftwareConsortium/itk-viewer pull request #77
Opened 2023-10-06 21:11 UTC by PaulHax

Changes rendered frame size based on client canvas size.

2023-10-06 21:24 UTC, thewtex requested changes
Nice!!

Minor naming suggestions inline

2023-10-06 21:24 UTC, thewtex commented on packages/agave-renderer/itk_viewer_agave_renderer/renderer.py
> +    def set_size(self, width, height):
set_size -> set_render_size

2023-10-06 21:24 UTC, thewtex commented on packages/agave-renderer/itk_viewer_agave_renderer/renderer.py
> +                case 'size':
renderSize

2023-10-06 21:40 UTC, PaulHax commented on packages/agave-renderer/itk_viewer_agave_renderer/renderer.py
> +                case 'size':
changed!

2023-10-07 12:16 UTC, thewtex commented on packages/agave-renderer/itk_viewer_agave_renderer/renderer.py
> +                case 'size':
:100:

2023-10-07 12:17 UTC, thewtex approved these changes
:100:

2023-10-07 12:17 UTC, merged